version: '2'
services:
  web:
    build: web
    ports:
      - "8000:8000"
    env_file: ./web/.env
    depends_on:
      - web-service
  courier-app:
    build: courier-app
    volumes:
      - './courier-app:/usr/src/app'
    ports:
      - '4200:4200'
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
  web-service:
    build: web-service
    ports:
      - "8080:8080"
    env_file: ./web-service/.env
    #depends_on:
    #  - redis
  #redis:
  #  image: redis:alpine
  #  ports:
  #    - "6379:6379"